# Main deployment for API server
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: server
  namespace: staging-web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        imagePullPolicy: Always
        image: loklak/loklak_server:latest-kubernetes-staging
        livenessProbe:
          httpGet:
            path: /api/status.json
            port: 80
          initialDelaySeconds: 90
          periodSeconds: 300
          timeoutSeconds: 3
        ports:
        - containerPort: 80
          protocol: TCP
