# Setup PVC for smooth switchover while updating image
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: server-data-claim
  namespace: web
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
