# Configuration of persistent volume
# gcloud compute disks create --size=100GB --zone=... data-index-disk
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-index-disk
  namespace: web
  labels:
    name: data-index-disk
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: data-index-disk
    fsType: ext4
